### ISSUE TITLE
Implement functions for transformation of entropy to mnemonic phrase and vice versa

### ISSUE THREAD

**Issue by sobuch** [mvondracek/PA193_mnemonic_Slytherin#11]

**Comment by mvondracek** [comment]
Related https://github.com/mvondracek/PA193_mnemonic_Slytherin/pull/19#discussion_r334274750 , https://github.com/mvondracek/PA193_mnemonic_Slytherin/issues/12#issuecomment-543391802, https://github.com/mvondracek/PA193_mnemonic_Slytherin/pull/19#discussion_r335151549.

We need to test our program with malicious dictionaries.
