### ISSUE TITLE
dictionary not included in installed package?

### ISSUE THREAD

**Issue by sobuch** [mvondracek/PA193_mnemonic_Slytherin#50]
Please find out whether you can reproduce the issue by following steps:
1) install using 'python setup.py install' 
2) create valid entropy file test 'echo -n "00112233445566778899aabbccddeeff" > test'
3) call generate with correct parameters 'mnemoniccli -g -e test -m testmnemonic -s testseed'

After completing above steps, I get error "[Errno 2] No such file or directory: 'C:\\Users\\samue\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pa193_mnemonic_slytherin-0.1.0-py3.7.egg\\PA193_mnemonic_Slytherin\\english.txt'
" on windows and "[Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/PA193_mnemonic_Slytherin-0.1.0-py3.6.egg/PA193_mnemonic_Slytherin/english.txt'" on linux

**Comment by mvondracek** [comment]
Hi, thank's for the report! I don't think package resources are configured, yet. I will look at it and fix it as soon as we finish review of #41 that I've been working on.
