### ISSUE TITLE
Testing against reference implementation and others

### ISSUE THREAD

**Issue by mvondracek** [mvondracek/PA193_mnemonic_Slytherin#56]
- [x] script to install reference implementation (https://github.com/trezor/python-mnemonic)
- [x] script to test our `mnemoniccli` against reference implementation
  - generate input data (random entropy, valid mnemonic, invalid mnemonic, valid seed, invalid seed, matching mnemonic-seed pair, non-matching mnemonic-seed pair)
  - run reference implementation, run `mnemoniccli` for the same inputs and the same task
  - test if outputs are the same
  - loop 😄

**Comment by mvondracek** [comment]
@lsolodkova, could you please take this?

**Comment by lsolodkova** [comment]
What is the best way to generate input data? How much do we need?

**Comment by mvondracek** [comment]
You could generate entropy as random bytes and it could run in loop.

**Comment by mvondracek** [comment]
Any progress so far? :)

**Comment by lsolodkova** [comment]
Dealing with #51 and #52 at the moment.

**Comment by mvondracek** [comment]
@sobuch, could you please take this?

**Comment by sobuch** [comment]
whats the decision about https://github.com/mvondracek/PA193_mnemonic_Slytherin/issues/3#issuecomment-546587983 ? it would be the simplest (best?) to test the same imputs, but we take inputs from different sources
