### ISSUE TITLE
EAFP vs LBYL, asserts

### ISSUE THREAD

**Issue by mvondracek** [mvondracek/PA193_mnemonic_Slytherin#6]
EAFP is more natural for Python, is it inevitably less secure? Is LBYL really more secure?

What about type assertions vs duck typing?

---
EAFP "It’s easier to ask for forgiveness than permission." 
LBYL: "Look before you leap."

**Comment by sobuch** [comment]
seems we have this sorted out, in short: EAF is valid, we should check user inputs before they reach the core functionality though
